replicaCount: 1
image:
  repository: 975050272810.dkr.ecr.us-east-1.amazonaws.com/frontend
  pullPolicy: Always


serviceAccount:
  create: true
  annotations: {}


securityContext: {}
service:
  type: ClusterIP
  port: 80
  containerPort: 80

resources:
   limits:
     cpu: 250m
     memory: 512Mi
   requests:
     cpu: 250m
     memory: 512Mi
